export const GET_COURSE = 'GET_COURSE';
export const GET_COURSES = 'GET_COURSES';
export const COURSES_LOADING = 'COURSES_LOADING';
export const CREATE_COURSE = 'CREATE_COURSE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
